# Generated by Django 5.1.4 on 2025-01-16 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TherapyQuestionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seeking_reason', models.TextField()),
                ('issue_duration', models.CharField(max_length=50)),
                ('previous_therapy', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('therapy_goals', models.TextField()),
                ('preferred_times', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
