# Generated by Django 5.1.4 on 2025-01-16 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='questions_p',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q1', models.TextField(verbose_name='Why are you seeking therapy?')),
                ('q2', models.CharField(max_length=50, verbose_name='How long have you been experiencing these issues?')),
                ('q3', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, verbose_name='Have you sought therapy before?')),
                ('q4', models.TextField(verbose_name='What are your goals for therapy?')),
                ('q5', models.CharField(max_length=100, verbose_name='Preferred days and times for sessions')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='TherapyQuestionnaire',
        ),
    ]
