# Generated by Django 5.1.4 on 2025-01-19 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0006_userprofile_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='TherapyQuestionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q1', models.TextField(help_text='Why are you seeking therapy?')),
                ('q2', models.CharField(choices=[('Less than 1 month', 'Less than 1 month'), ('1-6 months', '1-6 months'), ('6-12 months', '6-12 months'), ('Over a year', 'Over a year')], help_text='How long have you been experiencing these issues?', max_length=50)),
                ('q3', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], help_text='Have you sought therapy before?', max_length=3)),
                ('q4', models.TextField(help_text='What are your goals for therapy?')),
                ('q5', models.CharField(help_text='Preferred days and times for sessions', max_length=255)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
