# Generated by Django 5.1.4 on 2025-01-22 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0007_therapyquestionnaire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='password',
        ),
    ]
