# Generated by Django 5.1.4 on 2025-01-22 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0009_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'login_table',
            },
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
