# Generated by Django 5.1.4 on 2025-01-22 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0010_login_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Therapist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('specialization', models.CharField(max_length=200)),
                ('years_experience', models.IntegerField()),
                ('ratings', models.FloatField()),
                ('charges_per_hour', models.FloatField()),
                ('session_type', models.CharField(choices=[('individual', 'Individual'), ('couple', 'Couple'), ('family', 'Family')], max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Login',
        ),
    ]
