# Generated by Django 5.1.4 on 2025-01-23 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0013_booking_delete_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('paypal', 'PayPal'), ('creditCard', 'Credit Card')], max_length=20)),
                ('paypal_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('card_number', models.CharField(blank=True, max_length=16, null=True)),
                ('card_holder_name', models.CharField(blank=True, max_length=100, null=True)),
                ('expiry_date', models.CharField(blank=True, max_length=5, null=True)),
                ('cvv', models.CharField(blank=True, max_length=4, null=True)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
